<?php

namespace Ebay\Sell\Listing\Model;

use OpenAPI\Runtime\AbstractModel as AbstractModel;

/**
 * The type that defines the fields for the listing details.
 */
class ItemDraft extends AbstractModel
{
    /**
     * The ID of the leaf category associated with this item. A leaf category is the
     * lowest level in that category and has no children. Note: If you submit both a
     * category ID and an EPID, eBay determines the best category based on the EPID and
     * uses that. The category ID will be ignored.
     *
     * @var string
     */
    public $categoryId = null;

    /**
     * The enumeration value passed in here sets the condition of the item, such as NEW
     * or USED_EXCELLENT. See ConditionEnum for the full list of supported values.
     * Supported item conditions can vary by eBay category. To see which item
     * conditions are supported for a category, you can use the
     * getItemConditionPolicies method of the Metadata API. Note: The 'Manufacturer
     * Refurbished' item condition is no longer a valid item condition in any eBay
     * marketplace, and to reflect this change, the pre-existing
     * MANUFACTURER_REFURBISHED enumeration value has been replaced by the
     * CERTIFIED_REFURBISHED enumeration value. CR-eligible sellers should make a note
     * to start using CERTIFIED_REFURBISHED from this point forward. To list an item as
     * 'Certified Refurbished', a seller must be pre-qualified by eBay for this
     * feature. Any seller who is not eligible for this feature will be blocked if they
     * try to create a new listing or revise an existing listing with this item
     * condition. Any seller that is interested in eligibility requirements to list
     * with 'Certified Refurbished' should see the Certified refurbished program page
     * in Seller Center. For implementation help, refer to <a
     * href='https://developer.ebay.com/api-docs/sell/listing/types/api:ConditionEnum'>eBay
     * API documentation</a>.
     *
     * @var string
     */
    public $condition = null;

    /**
     * The container that for the information about the cost of an item, such as the
     * price or auction start price.
     *
     * @var \Ebay\Sell\Listing\Model\PricingSummary
     */
    public $pricingSummary = null;

    /**
     * The container for the product details of the item.
     *
     * @var \Ebay\Sell\Listing\Model\Product
     */
    public $product = null;

    /**
     * This container is used to identify the charitable organization that will receive
     * a percentage of sale proceeds for each sale generated by the listing. This
     * container consists of the charityId field to identify the charitable
     * organization, and the donationPercentage field that will set the percentage of
     * the sales proceeds that will be donated to the charitable organization.
     *
     * @var \Ebay\Sell\Listing\Model\Charity
     */
    public $charity = null;
}
